-- 다중행 함수
SELECT SUM(SAL) AS TOTAL FROM EMP;
SELECT TRUNC(AVG(SAL)) AS AVG_SAL FROM EMP;
SELECT TO_CHAR(AVG(SAL), '$999,999') AS AVG_SAL FROM EMP;
SELECT COUNT(*) FROM EMP;
SELECT COUNT(COMM) FROM EMP;
SELECT COUNT(JOB) FROM EMP;
SELECT COUNT(DISTINCT JOB) FROM EMP;

SELECT SUM(SAL) AS SUM_SAL,
MAX(SAL) AS MAX_SAL, 
TRUNC(AVG(SAL), 2) AS AVG_SAL
FROM EMP;

SELECT AVG(DISTINCT SAL) FROM EMP 
WHERE DEPTNO = 30;

SELECT AVG(SAL) FROM EMP
WHERE DEPTNO = 30;

-- GROUP BY
SELECT * FROM EMP;
SELECT DEPTNO, JOB, AVG(SAL) AS TOTAL FROM EMP GROUP BY JOB, DEPTNO;
SELECT JOB, TO_CHAR(MAX(SAL), '$999,999') AS MAX_SAL FROM EMP GROUP BY JOB;

SELECT JOB,
COUNT(JOB) AS COUNT_JOB,
TO_CHAR(SUM(SAL), '$999,999') AS SUM_SAL,
TO_CHAR(MAX(SAL), '$999,999') AS MAX_SAL, 
TO_CHAR(TRUNC(AVG(SAL)), '$999,999') AS AVG_SAL
FROM EMP GROUP BY JOB;

SELECT DEPTNO,
COUNT(DEPTNO) AS COUNT_DN,
TO_CHAR(SUM(SAL), '$999,999') AS SUM_SAL,
TO_CHAR(MAX(SAL), '$999,999') AS MAX_SAL, 
TO_CHAR(TRUNC(AVG(SAL)), '$999,999') AS AVG_SAL
FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO,
MIN(SAL) AS MIN_SAL FROM EMP GROUP BY DEPTNO;

-- 그룹 바이는 편리하다 (없었으면 유니온 올)
SELECT DEPTNO, TRUNC(AVG(SAL)) AS AVG_SAL 
FROM EMP 
GROUP BY DEPTNO ORDER BY DEPTNO ASC;

SELECT '10' AS DEPTNO, TRUNC(AVG(SAL)) AS AVG_SAL 
FROM EMP WHERE DEPTNO = 10 UNION ALL
SELECT '20' AS DEPTNO, TRUNC(AVG(SAL)) AS AVG_SAL 
FROM EMP WHERE DEPTNO = 20 UNION ALL
SELECT '30' AS DEPTNO, TRUNC(AVG(SAL)) AS AVG_SAL 
FROM EMP WHERE DEPTNO = 30;

SELECT 
DEPTNO, JOB, AVG(SAL) FROM EMP 
GROUP BY DEPTNO, JOB 
ORDER BY DEPTNO, JOB;

SELECT
DEPTNO, JOB, AVG(SAL) FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 1500
ORDER BY DEPTNO, JOB;

-- 순서
-- 1.WHERE 2.GROUP BY 3.HAVING 4.ORDER BY
SELECT * FROM EMP ORDER BY JOB;
-- 1
SELECT 
DEPTNO, TRUNC(AVG(SAL)) AS AVG_SAL, MAX(SAL) AS MAX_SAL,
MIN(SAL) AS MIN_SAL, COUNT(*) AS CNT FROM EMP 
GROUP BY DEPTNO;

-- 2
SELECT JOB, COUNT(*) FROM EMP 
GROUP BY JOB HAVING COUNT(*) >= 3;

-- 3
SELECT 
SUBSTR(TO_CHAR(HIREDATE, 'YYYY-MM-DD'), 1, 4) AS HIRE_YEAR, 
DEPTNO, COUNT(*) AS CNT
FROM EMP
GROUP BY SUBSTR(TO_CHAR(HIREDATE, 'YYYY-MM-DD'), 1, 4), DEPTNO
ORDER BY HIRE_YEAR;

-- 4
SELECT NVL2(COMM, 'O', 'X') AS EXIST_COMM, 
COUNT(*) AS CNT FROM EMP GROUP BY NVL2(COMM, 'O', 'X');
