INSERT INTO MEMBER (USERID, USERPW) VALUES ('YONEE001', '0000');
INSERT INTO MEMBER (USERID, USERPW) VALUES ('yonee001', '0000');
SELECT * FROM MEMBER;

ALTER TABLE MEMBER ADD USERNAME VARCHAR(10);
ALTER TABLE MEMBER ADD GENDER VARCHAR(10);
ALTER TABLE MEMBER ADD GRADE VARCHAR(10);

COMMIT;
ROLLBACK;